import { Component, OnInit, ViewChild } from '@angular/core';
import { Router } from '@angular/router';
import { ToastController, IonModal } from '@ionic/angular';

interface Cobertura {
  todoAuto: SelectCampos[];
  activa: SelectCampos[];
  rest: SelectCampos[];
}

interface SelectCampos {
  quoteId: string;
  name: string;
  selected: boolean;
  prizeAmount: number;
  commercialProductDesc: string;
}
@Component({
  selector: 'app-home',
  templateUrl: 'home.page.html',
  styleUrls: ['home.page.scss'],
})
export class HomePage implements OnInit {
  campos: SelectCampos[] = [];
  dataSource2 = [
    {
      quoteId: 'W155448411',
      commercialProductCode: '3101',
      coverages: [
        {
          coverageId: '90',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1001',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1003',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1005',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1103',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '11',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 2500,
          requiredInd: null,
          deductibleValue: null,
        },
      ],
      vehiAgeUpTo: 20,
      commercialProductName: 'POLIZA BASICA',
      commercialProductDesc: null,
      prizeAmount: 339004.69,
    },
    {
      quoteId: 'W155448407',
      commercialProductCode: '1402',
      vehiAgeUpTo: 15,
      coverages: [
        {
          coverageId: '48',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '90',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1001',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1003',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1005',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1006',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1007',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1103',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '11',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 2500,
          requiredInd: null,
          deductibleValue: null,
        },
      ],
      commercialProductName: 'ACTIVA',
      commercialProductDesc: null,
      prizeAmount: 5135.04,
    },
    {
      quoteId: 'W155448408',
      commercialProductCode: '1409',
      vehiAgeUpTo: 15,
      coverages: [
        {
          coverageId: '48',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '90',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1001',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1003',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1005',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1006',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1007',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1103',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1111',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '11',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 2500,
          requiredInd: null,
          deductibleValue: null,
        },
      ],
      commercialProductName: 'ACTIVA',
      commercialProductDesc: 'GRANIZO',
      prizeAmount: 5316.03,
    },
    {
      quoteId: 'W155448409',
      commercialProductCode: '1410',
      vehiAgeUpTo: 15,
      coverages: [
        {
          coverageId: '48',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '90',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1001',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1003',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1005',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1006',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1007',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1013',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '10',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1103',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '11',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 2500,
          requiredInd: null,
          deductibleValue: null,
        },
      ],
      commercialProductName: 'ACTIVA',
      commercialProductDesc: 'CRISTALES',
      prizeAmount: 5570.1,
    },
    {
      quoteId: 'W155448410',
      commercialProductCode: '1408',
      vehiAgeUpTo: 15,
      coverages: [
        {
          coverageId: '48',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '90',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1001',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1003',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1005',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1006',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1007',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1013',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '10',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1103',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1111',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '11',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 2500,
          requiredInd: null,
          deductibleValue: null,
        },
      ],
      commercialProductName: 'ACTIVA',
      commercialProductDesc: 'CRISTALES Y GRANIZO',
      prizeAmount: 5751.11,
    },
    {
      quoteId: 'W155448406',
      commercialProductCode: '1209',
      vehiAgeUpTo: 10,
      coverages: [
        {
          coverageId: '48',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '90',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1001',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1003',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1005',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1006',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1007',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1013',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '10',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1020',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1103',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1111',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1114',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1115',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '11',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 5000,
          requiredInd: null,
          deductibleValue: null,
        },
      ],
      commercialProductName: 'POLIZA 10',
      commercialProductDesc: null,
      prizeAmount: 5820.24,
    },
    {
      quoteId: 'W155448412',
      commercialProductCode: '4409',
      vehiAgeUpTo: 5,
      coverages: [
        {
          coverageId: '48',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '90',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1001',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1003',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1005',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1006',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1007',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1010',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1013',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '10',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1020',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1103',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1111',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1114',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1115',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '11',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 10000,
          requiredInd: null,
          deductibleValue: null,
        },
      ],
      commercialProductName: 'NUEVA TODO AUTO',
      commercialProductDesc: 'FRANQUICIA FIJA',
      prizeAmount: 10143.93,
    },
    {
      quoteId: 'W155448413',
      commercialProductCode: '4409',
      vehiAgeUpTo: 5,
      coverages: [
        {
          coverageId: '48',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '90',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1001',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1003',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1005',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1006',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1007',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1010',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1013',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '10',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1020',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1103',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1111',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1114',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1115',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '11',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 10000,
          requiredInd: null,
          deductibleValue: null,
        },
      ],
      commercialProductName: 'NUEVA TODO AUTO',
      commercialProductDesc: 'FRANQUICIA VARIABLE 1%',
      prizeAmount: 9430.39,
    },
    {
      quoteId: 'W155448414',
      commercialProductCode: '4409',
      vehiAgeUpTo: 5,
      coverages: [
        {
          coverageId: '48',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '90',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1001',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1003',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1005',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1006',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1007',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1010',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1013',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '10',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1020',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1103',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1111',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1114',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1115',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '11',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 10000,
          requiredInd: null,
          deductibleValue: null,
        },
      ],
      commercialProductName: 'NUEVA TODO AUTO',
      commercialProductDesc: 'FRANQUICIA VARIABLE 2%',
      prizeAmount: 9151.96,
    },
    {
      quoteId: 'W155448415',
      commercialProductCode: '4409',
      vehiAgeUpTo: 5,
      coverages: [
        {
          coverageId: '48',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '90',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1001',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1003',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1005',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1006',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1007',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1010',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1013',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '10',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1020',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1103',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1111',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1114',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1115',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '11',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 10000,
          requiredInd: null,
          deductibleValue: null,
        },
      ],
      commercialProductName: 'NUEVA TODO AUTO',
      commercialProductDesc: 'FRANQUICIA VARIABLE 3%',
      prizeAmount: 8873.51,
    },
    {
      quoteId: 'W155448416',
      commercialProductCode: '4409',
      vehiAgeUpTo: 5,
      coverages: [
        {
          coverageId: '48',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '90',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1001',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1003',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1005',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1006',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1007',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1010',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1013',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '10',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1020',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1103',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1111',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1114',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1115',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '11',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 10000,
          requiredInd: null,
          deductibleValue: null,
        },
      ],
      commercialProductName: 'NUEVA TODO AUTO',
      commercialProductDesc: 'FRANQUICIA VARIABLE 5%',
      prizeAmount: 8421.02,
    },
    {
      quoteId: 'W155448417',
      commercialProductCode: '4409',
      vehiAgeUpTo: 5,
      coverages: [
        {
          coverageId: '48',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '90',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1001',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1003',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1005',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1006',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1007',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1010',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1013',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '10',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1020',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1103',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1111',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1114',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1115',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '11',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 10000,
          requiredInd: null,
          deductibleValue: null,
        },
      ],
      commercialProductName: 'NUEVA TODO AUTO',
      commercialProductDesc: 'FRANQUICIA VARIABLE 10%',
      prizeAmount: 7516.04,
    },
    {
      quoteId: 'W155448418',
      commercialProductCode: '1502',
      vehiAgeUpTo: 10,
      coverages: [
        {
          coverageId: '90',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1001',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1003',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1005',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1103',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1111',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '11',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 2500,
          requiredInd: null,
          deductibleValue: null,
        },
      ],
      commercialProductName: 'BASICA IN',
      commercialProductDesc: null,
      prizeAmount: 9005.23,
    },
    {
      quoteId: 'W155448419',
      commercialProductCode: '1602',
      vehiAgeUpTo: 10,
      coverages: [
        {
          coverageId: '48',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '90',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1001',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1003',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1005',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1006',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1007',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1013',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '10',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1103',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1111',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '11',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 2500,
          requiredInd: null,
          deductibleValue: null,
        },
      ],
      commercialProductName: 'XPRESS CAR',
      commercialProductDesc: null,
      prizeAmount: 16600049.09,
    },
    {
      quoteId: 'W155448420',
      commercialProductCode: '1702',
      vehiAgeUpTo: 10,
      coverages: [
        {
          coverageId: '48',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '90',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1001',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1003',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1005',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1006',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1007',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1010',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1013',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '10',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1020',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1103',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '1114',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 0,
          requiredInd: null,
          deductibleValue: null,
        },
        {
          coverageId: '11',
          coverageTitle: null,
          coverageDesc: null,
          coveragePeriodNum: null,
          currencyIsoCode: null,
          coverageAmn: null,
          sumInsuredAmn: 2500,
          requiredInd: null,
          deductibleValue: null,
        },
      ],
      commercialProductName: 'PREMIUM CAR',
      commercialProductDesc: 'FRANQUICIA 5%',
      prizeAmount: 24570008.58,
    },
  ];
  mensaje: string = '';
  coberturas?: Cobertura = {
    activa: [],
    todoAuto: [],
    rest: []
  };
  @ViewChild(IonModal) modal!: IonModal;
  constructor(
    private _router: Router,
    private toastController: ToastController
  ) {}

  ngOnInit() {
    this.dataSource2.forEach((element) => {
      const e = {
        name: element.commercialProductName,
        quoteId: element.quoteId,
        prizeAmount: element.prizeAmount,
        commercialProductDesc: element.commercialProductDesc || 'GENERICA',
        selected: false,
      }
      switch (element.commercialProductName) {
        case 'ACTIVA':
          this.coberturas?.activa.push(e);
          break;
        case 'POLIZA 10':
          this.coberturas?.activa.push(e);
          break;
        case 'NUEVA TODO AUTO':
          this.coberturas?.todoAuto.push(e);
          break;
        default:
          this.coberturas?.rest.push(e);
          break;
      }
    });
    // this.dataSource2.forEach((e: any) => {
    //   this.campos.push({
    //     name: e.commercialProductName,
    //     quoteId: e.quoteId,
    //     prizeAmount: e.prizeAmount,
    //     selected: false,
    //   });
    // });
  }
  cancel() {
    this.modal.dismiss(null, 'cancel');
  }
  async verTabla() {
    let sum = 0;
    let polizasAMostrar: SelectCampos[] = [];
    this.coberturas?.activa.forEach((element) => {
      if (element.selected) {
        sum++;
        polizasAMostrar.push(element);
      }
    });
    this.coberturas?.rest.forEach((element) => {
      if (element.selected) {
        sum++;
        polizasAMostrar.push(element);
      }
    });
    this.coberturas?.todoAuto.forEach((element) => {
      if (element.selected) {
        sum++;
        polizasAMostrar.push(element);
      }
    });
    if (sum >= 9) {
      const toast = await this.toastController.create({
        message: 'Ingrese 9 o menos campos',
        duration: 2000,
        position: 'top',
        color: 'danger',
      });
      await toast.present();
    } else {
      let retorno: any = [];
      polizasAMostrar.forEach((a) => {
        if (a.selected) {
          retorno.push(this.dataSource2.find((e) => e.quoteId === a.quoteId));
        }
      });
      localStorage.setItem('polizas', JSON.stringify(retorno));
      this.modal.dismiss(null, 'show table');
      this._router.navigate(['/table']);
    }
  }
}
